### ISSUE TITLE
flex+margin 布局

### ISSUE THREAD

**Issue by vincentzyc** [vincentzyc/notes#22]
```html
<div class="automargin">
  <div class="child">child</div>
</div> 
```
```css
.automargin{
display:flex;
}
.child{
margin:auto;  //垂直居中
margin-left: auto  //居右
margin-top: auto  //居下
}
```
