### ISSUE TITLE
多个子元素自适应宽度水平居中

### ISSUE THREAD

**Issue by vincentzyc** [vincentzyc/notes#44]
```html
<ul class="items">
  <li>111</li>
  <li>222</li>
  <li>333</li>
  <li>444</li>
  <li>555</li>
</ul>
```

```css
.items {
  text-align:center;
} 
.items li {
  display: inline-block;
  width: 200px;
  height: 150px;
  border:1px solid #ccc;
}
```
