### ISSUE TITLE
文本超出部分显示省略号

### ISSUE THREAD

**Issue by vincentzyc** [vincentzyc/notes#54]
```css
/* 必须固定宽度 */
.textover {
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
}
/* 可用于flex布局自适应宽度 */
.textover1 {
    overflow: hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 1;
    -webkit-box-orient: vertical;
}
.textover2 {
    overflow: hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
}
.textover3 {
    overflow: hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
}
```

###  注意！！！
上面的 textover1 ，textover2 ，textover3 有时候可能无效，加上 white-space: pre-line; 或者 white-space: pre-wrap; 即可；例如：

```
.textover2 {
    overflow: hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    white-space: pre-line;
}
```

white-space:
|  值   |   描述  |
| --- | --- |
|normal	   | 默认。空白会被浏览器忽略。|
|pre	   | 空白会被浏览器保留。其行为方式类似 HTML 中的 < pre > 标签。|
|nowrap	   | 文本不会换行，文本会在在同一行上继续，直到遇到 < br > 标签为止。|
|pre-wrap  | 保留空白符序列，但是正常地进行换行。|
|pre-line  | 合并空白符序列，但是保留换行符。|
|inherit   | 规定应该从父元素继承 white-space 属性的值。|
