### ISSUE TITLE
ios 下 input 在 disabled 的时候，设置背景颜色无效

### ISSUE THREAD

**Issue by vincentzyc** [vincentzyc/notes#62]
```css
input:disabled { 
  background-color: #fff;
  opacity:1
}
```
