### ISSUE TITLE
ios 下 input 在 disabled 的时候，设置背景和字体颜色无效

### ISSUE THREAD

**Issue by vincentzyc** [vincentzyc/notes#64]
设置背景颜色无效解决方法：
```css
input:disabled { 
  background-color: #fff;
  opacity:1
}
```

设置字体颜色无效解决方法：
```css
input:disabled{  
    color:#666;
    opacity: 1;
    -webkit-text-fill-color: #666;
}
```
