### ISSUE TITLE
ios下使用动画 transform: translate(xx%) 无效问题

### ISSUE THREAD

**Issue by vincentzyc** [vincentzyc/notes#69]
```html
<div class="wg-marquee-up"></div>
```

```css
  .wg-marquee-up {
    height:300px;
    -webkit-animation: marquee-up 5s linear infinite;
    -ms-animation: marquee-up 5s linear infinite;
    -o-animation: marquee-up 5s linear infinite;
    animation: marquee-up 5s linear infinite;
  }
  @keyframes marquee-up {
	0% {
		transform: translateY(0);
	}

	100% {
		transform: translateY(-50%);
	}
   }
```
动画效果：安卓正常，ios无效

#### ios无效解决方法：给动画加个延迟 

```
animation: marquee-up 5s 0.1s linear infinite
```
